@startuml ActividadesYFormaciones
!pragma useVerticalIf on

skinparam ConditionEndStyle hline

title Diagrama de actividades: Actividades y Formaciones

start

:Comprobar rol;

if (¿Es monitor/coordinador?) then (Sí)
    :Seleccionar acción;

    if (¿Acción == Crear?) then (Sí)
        :Crear actividad;

    elseif (¿Acción == Visualizar?) then (Sí)
        :Visualizar actividad;

    elseif (¿Acción == Evaluar?) then (Sí)
        if (¿Es actividad o formación?) then (Actividad)
            :Evaluar actividad;

        else (Formación)
            :Acción inválida;

        endif

    elseif (¿Acción == Modificar?) then (Sí)
        if (¿Monitor o coordinador?) then (Monitor)
            if (¿Ha pasado la fecha de la actividad?) then (Sí)
                :Acción inválida;

            else (No)
                :Modificar actividad;

            endif

        else (Coordinador)
            :Modificar actividad;

        endif

    elseif (¿Acción == Eliminar?) then (Sí)
        if (¿Monitor o coordinador?) then (Monitor)
            if (¿Ha pasado la fecha de la actividad?) then (Sí)
                :Acción inválida;

            else (No)
                :Eliminar actividad;

            endif

        else (Coordinador)
            :Eliminar actividad;

        endif

    else
        :Acción no válida;

    endif

else (No)
    if (¿Es socio?) then (Sí)
        :Seleccionar acción;

        if (¿Acción == Ver?) then (Sí)
            :Consultar actividades;

        elseif (¿Acción == Apuntar?) then (Sí)
            :Apuntarse a una actividad;

        elseif (¿Acción == Desapuntar?) then (Sí)
            :Desapuntarse de una actividad;

        else
            :Acción no válida;

        endif

    else (No)
        :Rol inválido;

    endif
endif

stop
@enduml