@startuml RolesYPermisos
!pragma useVerticalIf on

skinparam ConditionEndStyle hline

title Diagrama de actividades: Roles y Permisos

start

:Comprobar rol;

if (¿Es coordinador?) then (Sí)
    :Seleccionar acción;

    if (¿Acción == Crear?) then (Sí)
        :Crear rol;

    elseif (¿Acción == Asignar permiso?) then (Sí)
        :Asignar permiso a un rol;

    elseif (¿Acción == Asignar rol?) then (Sí)
        :Asignar rol a un usuario;

    elseif (¿Acción == Desasignar rol?) then (Sí)
        :Desasignar rol a un usuario;

    elseif (¿Acción == Habilitar?) then (Sí)
        :Habilitar rol;

    elseif (¿Acción == Inhabilitar?) then (Sí)
        :Inhabilitar rol;

    else
        :Acción no válida;

    endif

else (No)
    if (¿Es monitor?) then (Sí)
        :Seleccionar acción;

        if (¿Acción == Crear?) then (Sí)
            :Consultar roles;

        else (No)
            :Acción no válida;

        endif

    else (No)
        :Rol inválido;

    endif
endif

stop
@enduml